```groovy
// this process runs MultiQC to aggregate results from multiple bioinformatics tools
process MULTIQC {
    // label for the process
    label 'process_single'

    // specifies the conda environment to use
    conda "${moduleDir}/environment.yml"
    // selects the appropriate container based on conditions
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/multiqc:1.25.1--pyhdfd78af_0' :
        'biocontainers/multiqc:1.25.1--pyhdfd78af_0' }"

    // input section for the files needed by MultiQC
    input:
    path  multiqc_files, stageAs: "?/*" // path to MultiQC input files
    path(multiqc_config) // path to MultiQC configuration file
    path(extra_multiqc_config) // path to additional MultiQC configuration file
    path(multiqc_logo) // path to custom logo for MultiQC report
    path(replace_names) // path to file for name replacements in the report
    path(sample_names) // path to file containing sample names

    // output section for the files generated by MultiQC
    output:
    path "*multiqc_report.html", emit: report // output report file
    path "*_data"              , emit: data // output data files
    path "*_plots"             , optional:true, emit: plots // optional output for plots
    path "versions.yml"        , emit: versions // output file for version information

    // condition under which the task should run
    when:
    task.ext.when == null || task.ext.when

    // script section that contains the command to run MultiQC
    script:
    def args = task.ext.args ?: '' // retrieves additional arguments if provided
    def prefix = task.ext.prefix ? "--filename ${task.ext.prefix}.html" : '' // sets output filename if prefix is provided
    def config = multiqc_config ? "--config $multiqc_config" : '' // adds configuration file option if provided
    def extra_config = extra_multiqc_config ? "--config $extra_multiqc_config" : '' // adds extra config file option if provided
    def logo = multiqc_logo ? "--cl-config 'custom_logo: \"${multiqc_logo}\"'" : '' // adds logo option if provided
    def replace = replace_names ? "--replace-names ${replace_names}" : '' // adds name replacement option if provided
    def samples = sample_names ? "--sample-names ${sample_names}" : '' // adds sample names option if provided
    """
    // command to execute MultiQC with the specified options
    multiqc \\
        --force \\
        $args \\
        $config \\
        $prefix \\
        $extra_config \\
        $logo \\
        $replace \\
        $samples \\
        .

    // writes version information to versions.yml
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        multiqc: \$( multiqc --version | sed -e "s/multiqc, version //g" )
    END_VERSIONS
    """

    // stub section for creating a basic directory structure and files
    stub:
    """
    // creates directories and files for the MultiQC process
    mkdir multiqc_data
    mkdir multiqc_plots
    touch multiqc_report.html

    // writes version information to versions.yml in the stub
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        multiqc: \$( multiqc --version | sed -e "s/multiqc, version //g" )
    END_VERSIONS
    """
}
```