```
// this process indexes genomic files using SAMtools
process SAMTOOLS_INDEX {
    
    // tag for identifying the process
    tag "$meta.id"
    
    // label for the process
    label 'process_low'

    // specifies the conda environment to use for this process
    conda "${moduleDir}/environment.yml"
    
    // defines the container to be used, based on the workflow's container engine
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/samtools:1.21--h50ea8bc_0' :
        'biocontainers/samtools:1.21--h50ea8bc_0' }"

    // input section for the process, taking metadata and input path
    input:
    tuple val(meta), path(input)

    // output section defining the output files generated by the process
    output:
    tuple val(meta), path("*.bai") , optional:true, emit: bai
    tuple val(meta), path("*.csi") , optional:true, emit: csi
    tuple val(meta), path("*.crai"), optional:true, emit: crai
    path  "versions.yml"           , emit: versions

    // condition for when the process should run
    when:
    task.ext.when == null || task.ext.when

    // script section that contains the command to run SAMtools
    script:
    def args = task.ext.args ?: ''
    """
    samtools \\
        index \\
        -@ ${task.cpus-1} \\
        $args \\
        $input

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        samtools: \$(echo \$(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*\$//')
    END_VERSIONS
    """

    // stub section for handling cases where the process may not run the full script
    stub:
    def args = task.ext.args ?: ''
    def extension = file(input).getExtension() == 'cram' ?
                    "crai" : args.contains("-c") ?  "csi" : "bai"
    """
    touch ${input}.${extension}

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        samtools: \$(echo \$(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*\$//')
    END_VERSIONS
    """
}
```